#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
cppflags = env['CPPFLAGS']

if target == 'host':
	cppflags = ''

src = [ 'd3des.c', 'nanox.c', 'rfbproto.c', 'sockets.c', 'vncauth.c' ]

lib = env.StaticLibrary('vnc', src,
                        CPPFLAGS = cppflags,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])

inst = env.Install(libdir, lib)

Return('inst')
