#!/usr/bin/python
#
# libvnc
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
cppflags = env['CPPFLAGS']
vnc = env.Clone()

vnc.Replace(CCFLAGS = '-O3 -g')

if target == 'host':
	cppflags = ''

src = [ 'd3des.c', 'nanox.c', 'rfbproto.c', 'sockets.c', 'vncauth.c' ]

static = vnc.StaticLibrary('vnc', src,
                        CPPFLAGS = cppflags,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])
shared = vnc.SharedLibrary('vnc', src,
                        CPPFLAGS = cppflags,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])

inst = env.Install(libdir, [ static, shared ])

Return('inst')
