#!/usr/bin/python
#
# build libdvbpsi
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
    config = '--host=powerpc'
else:
    config = ''
  
e = Environment()

url = [ '%s/libdvbpsi4-0.1.5.tar.gz'%mvpmc.dlprefix,
        'http://download.videolan.org/pub/libdvbpsi/0.1.5/libdvbpsi4-0.1.5.tar.gz' ]

target = [ libdir + 'libdvbpsi.a',
           incdir + 'dvbpsi/dvbpsi.h' ]

cmd = [ './configure --prefix=%s %s' % (prefix,config),
        'make',
        'make install' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
