#!/usr/bin/python
#
# build libid3
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

config = '--enable-fixed'
if build_target == 'mvp':
    config = config + ' --host=powerpc'

e = Environment()

url = [ 'http://www.mvpmc.org/dl/libid3-1.0.tar.gz',
        'http://download.tangent.org/libid3-1.0.tar.gz' ]

target = [ libdir + 'libid3.a',
           incdir + 'id3.h' ]
cmd = [ './configure --prefix=%s %s' % (prefix,config),
        'make',
        'make install' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
