#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

import os

Import('env')

home = os.environ['HOME']
cross = env['CROSS']

pwd = os.getcwd()

downloads = home + '/downloads'

os.system(pwd + '/build_kernel.sh ' + downloads + ' ' + cross)
