#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

import os

Import('env')

cross = env['CROSS']

pwd = os.getcwd()

dongle = env.Command('../dongle.bin.mvpmc', 0,
                     'cd ' + pwd + ' && CROSS=' + cross + ' ./dongle.sh')

Return('dongle')
