--- dropbear-0.48.1/Makefile.in	2006-03-11 22:52:51.000000000 -0600
+++ dropbear-0.48.1-new/Makefile.in	2007-06-02 22:10:59.000000000 -0500
@@ -9,6 +9,9 @@
 # dbclient functionality, and includes the progress-bar functionality in scp.
 # Hopefully that seems intuitive.
 
+PROGRAMS=dropbear dropbearkey scp
+MULTI=1
+
 ifndef PROGRAMS
 	PROGRAMS=dropbear dbclient dropbearkey dropbearconvert
 endif
@@ -135,14 +138,18 @@
 
 # dropbear should go in sbin, so it needs a seperate rule
 inst_dropbear: dropbear
-	$(INSTALL) -d -m 755 $(DESTDIR)$(sbindir)
-	$(INSTALL) -m 755 dropbear$(EXEEXT) $(DESTDIR)$(sbindir)
+	install -d -m 755 $(DESTDIR)$(sbindir)
+	install -m 755 dropbear$(EXEEXT) $(DESTDIR)$(sbindir)
 	-chown root $(DESTDIR)$(sbindir)/dropbear$(EXEEXT)
 	-chgrp 0 $(DESTDIR)$(sbindir)/dropbear$(EXEEXT)
 
+inst_dropbearmulti: dropbearmulti
+	install -d -m 755 $(DESTDIR)$(sbindir)
+	install -m 755 dropbearmulti $(DESTDIR)$(sbindir)
+
 inst_%: $*
-	$(INSTALL) -d -m 755 $(DESTDIR)$(bindir)
-	$(INSTALL) -m 755 $*$(EXEEXT) $(DESTDIR)$(bindir)
+	install -d -m 755 $(DESTDIR)$(bindir)
+	install -m 755 $*$(EXEEXT) $(DESTDIR)$(bindir)
 	-chown root $(DESTDIR)$(bindir)/$*$(EXEEXT)
 	-chgrp 0 $(DESTDIR)$(bindir)/$*$(EXEEXT)
 
