#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#
# build microwindows
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
downloads = env['DOWNLOADS']
target = env['TARG']

if target == 'mvp':
  cross = '-c ' + env['CROSS']
  host = '--host=powerpc'
  Carg = '-C '
  patches = ''
else:
  cross = ''
  host = ''
  Carg = ''
  patches = '-p patches/microwindows-0.91_host.patch'

file = downloads + '/microwindows-src-0.91.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'ftp://microwindows.censoft.com/pub/microwindows/microwindows-src-0.91.tar.gz'
pwd = os.getcwd()

dl = GetSourceFile(url, '#' + downloads, e)

build = env.Command('../../install/' + target + '/lib/libnano-X.a', 0,
                    'scons/build_lib.sh -d ' + pwd + '/' + target +
                    '/microwindows-0.91 -i ' + file + ' ' +
                    cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target + ' ' +
                    Carg + host + ' ' +
                    '-p patches/microwindows-0.91_abs.patch ' +
                    '-p patches/microwindows-0.91.patch ' +
                    patches)

incdir = pwd + '/../../install/' + target + '/include'
cp = env.Command(incdir + '/nano-X.h', 0,
            'cp ' + pwd + '/' + target +
            '/microwindows-0.91/src/include/*.h ' + incdir)

env.Depends(build, dl)
env.Depends(cp, build)

env.SideEffect(['../../install/' + target + '/include/mwobjects.h',
                '../../install/' + target + '/include/mwtypes.h',
                '../../install/' + target + '/include/nxcolors.h',
                '../../install/' + target + '/include/nxdraw.h'],
               build)

Return('build')
