#!/usr/bin/python
#
# build flashcp
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)

e = Environment()

url = [ 'http://www.mvpmc.org/dl/mtd.tar.gz' ]

target = [ bindir + 'flashcp' ]
cmd = [ 'cd util',
        'make flashcp',
        'cp flashcp %s' % bindir ]
patches = []

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
