#!/usr/bin/python
#
# build flashcp
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
cross = env['CROSS']
downloads = env['DOWNLOADS']
target = env['TARG']

file = downloads + '/mtd.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'http://www.mvpmc.org/dl/mtd.tar.gz'
pwd = os.getcwd()

build = env.Command('../../install/' + target + '/bin/flashcp', 0,
                    'scons/build_app.sh -d ' + pwd + '/' + target +
                    '/mtd -i ' + file + ' ' +
                    '-c ' + cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target)

if not os.path.exists(file):
	dl = GetSourceFile(url, '#' + downloads, e)
	env.Depends(build, dl)

Return('build')
