#!/usr/bin/python
#
# build djmount
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)

e = Environment()

url = [ 'http://www.mvpmc.org/dl/djmount-0.71.tar.gz' ]

pwd = os.getcwd()

target = [ bindir + 'djmount' ]
cmd = [ './configure --host=powerpc-405-linux-uclibc --with-fuse-prefix=%s/../fuse/mvp/fuse-2.5.3/ --disable-debug --with-gnu-ld' % pwd,
        'make',
        'cp djmount/djmount %s' % bindir ]
patches = [ 'djmount.patch' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
