#!/usr/bin/python
#
# build Tremor
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/tremor/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

config = '--enable-fixed'
if build_target == 'mvp':
    config = config + ' --host=powerpc'
    autogen = '--enable-shared --host powerpc-linux-gnu'
else:
    autogen = '--disable-shared'

e = Environment()

url = [ '%s/tremor-1.0.2.tar.gz'%mvpmc.dlprefix ]

target = [ libdir + 'libvorbisidec.a',
           incdir + 'ivorbiscodec.h',
           incdir + 'ivorbisfile.h' ]
cmd = [ './autogen.sh %s --prefix=%s' % (autogen,prefix),
        'make',
        'make install' ]

if build_target == 'mvp':
    target.append(libdir + 'libvorbisidec.so')

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
