#!/usr/bin/python
#
# build nbtscan
# Author site http://www.inetcat.net/software/nbtscan.html
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)

e = Environment()

url = [ 'http://www.mvpmc.org/dl/nbtscan-1.5.1.tar.gz',
        'http://www.inetcat.net/software/nbtscan-1.5.1.tar.gz' ]

target = [ bindir + 'nbtscan' ]
cmd = [ './configure --host=powerpc',
        'make',
        'cp nbtscan %s' % bindir ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
