#!/usr/bin/python
#
# build squashfs-tools
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
cross = env['CROSS']
downloads = env['DOWNLOADS']
target = env['TARG']

file = downloads + '/squashfs2.2-r2.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

#url = 'http://surfnet.dl.sourceforge.net/squashfs/squashfs2.2-r2.tar.gz'
url = 'http://www.mvpmc.org/dl/squashfs2.2-r2.tar.gz'
pwd = os.getcwd()

build = env.Command(pwd + '/squashfs2.2-r2/squashfs-tools/mksquashfs', 0,
                    'cd ' + pwd + ' && tar -xzf ' + file + ' && '
                    'cd squashfs2.2-r2 && '
                    'patch -p1 <../patches/squashfs-devtab.patch && '
                    'cd squashfs-tools && '
                    'CC=gcc make')

env.Depends(build, [ 'patches/squashfs-devtab.patch' ])

if not os.path.exists(file):
	dl = GetSourceFile(url, '#' + downloads, e)
	env.Depends(build, dl)

Return('build')
