#!/usr/bin/python
#
# build squashfs-tools
#

import os
import mvpmc

Import('env')

e = Environment()

url = [ '%s/squashfs2.2-r2.tar.gz'%mvpmc.dlprefix0,
	'%s/squashfs2.2-r2.tar.gz'%mvpmc.dlprefix1,
	'http://surfnet.dl.sourceforge.net/squashfs/squashfs2.2-r2.tar.gz' ]

pwd = os.getcwd()

patches = [ 'patches/squashfs-devtab.patch' ]

target = [pwd + '/mksquashfs']

cmd = [ 'cd squashfs-tools',
	'CC=gcc make',
	'cp mksquashfs %s' % pwd ];

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
