#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

import os

Import('env')

cc = env['CC']
pwd = os.getcwd()

uclibc = os.system('cd ' + pwd + ' && ./mvpmc-uclibc.sh ' + cc)

Return('uclibc')
