#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

import os

Import('env')

home = os.environ['HOME']
downloads = env['DOWNLOADS']
target = env['TARG']
pwd = os.getcwd()

file = downloads + '/buildroot-20060710.tar.bz2'

url = 'http://buildroot.uclibc.org/downloads/snapshots/buildroot-20060710.tar.bz2'
uclibc = os.system(pwd +'/mvpmc-uclibc.sh '+file + ' ' + url)
uclibc = ''

Return('uclibc')
