#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

import os

Import('env')

home = os.environ['HOME']
cross = env['CROSS']

pwd = os.getcwd()

downloads = home + '/downloads'

kernel_31 = env.Command(pwd + '../../filesystem/kernel_files/vmlinux.gz', 0, 'cd ' + pwd + ' && ./build_kernel.sh ' + downloads + ' ' + cross)
fuseo = env.SConscript(['fuse/SConscript'])

kernel = env.Depends(fuseo,kernel_31)


Return('kernel')

