#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#
# build genext2fs
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
cross = env['CROSS']
downloads = env['DOWNLOADS']
target = env['TARG']

file = downloads + '/genext2fs-1.4rc1.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'http://mvpmc.sourceforge.net/dl/genext2fs-1.4rc1.tar.gz'
pwd = os.getcwd()

dl = GetSourceFile(url, '#' + downloads, e)

build = env.Command(pwd + '/genext2fs-1.4rc1/genext2fs', 0,
                    'cd ' + pwd + ' && tar -xzf ' + file + ' && '
                    'cd genext2fs-1.4rc1 && '
                    'CC=gcc ./configure && make')

env.Depends(build, dl)

Return('build')
