#!/usr/bin/python
#
# libtiwlan
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
bindir = env['INSTBINDIR']

src = [ 'tiwlan.c' ]

static = env.StaticLibrary('tiwlan', src, CPPPATH = [ env['INCDIR'], '.' ])
shared = env.SharedLibrary('tiwlan', src, CPPPATH = [ env['INCDIR'], '.' ])

inst = env.Install(libdir, [ static, shared ])

Return('inst')
