#!/usr/bin/python
#
# libosd
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']

src = [ 'cursor.c', 'gfx.c', 'init.c', 'fb.c', 'osd.c',
	'fonts/CaslonRoman-1.25.c']

static = env.StaticLibrary('osd', src, CPPPATH = [ env['INCDIR'], '.' ])
shared = env.SharedLibrary('osd', src, CPPPATH = [ env['INCDIR'], '.' ])

inst = env.Install(libdir, [ static, shared ])

if target == 'mvp':
	osdtest = env.Program('osdtest',
	      	              [ 'osdtest.c' ],
	                      CPPPATH = [ env['INCDIR'] ],
	                      LIBS = [ 'osd' ],
	                      LIBPATH = [ libdir ],
                              LINKFLAGS = [ '-static' ])
	env.Depends(osdtest, static)

Return('inst')
