#!/bin/sh
#
# Startup script for the wrapper filesystem
#

ROOTDEV=/dev/mtd5
ROOTBLK=/dev/mtdblock5

#
# Load all the kernel modules
#
insmod os_core
insmod av_core _fmt=1
insmod ircombo
insmod gfx
insmod osdfb
insmod ac3_mod
insmod mvpstb_mod.o mvpmod_major=230

mount -t proc /proc /proc

#
# Switch to the embedded filesystem, if it exists.
#
if [ -n /etc/rootfs.img ] ; then
    dd if=/etc/rootfs.img of=/dev/mtd5
    mount /dev/mtdblock5 /mnt
    cd /mnt
    /sbin/pivot_root . oldroot
    umount /oldroot/proc
    kill -QUIT 1
else
    echo embedded filesystem not found
fi
