#!/usr/bin/python
#
# build fusermount and library files 
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
sbindir = '%s/dongle/install/%s/sbin/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

e = Environment()

url = [ 'http://www.mvpmc.org/dl/fuse-2.5.3.tar.gz' ]

target = [ sbindir + 'fusermount' ]
cmd = [ './configure --host=powerpc-linux -with-gnu-ld --disable-debug  --enable-lib --enable-util --enable-example=no --disable-kernel-module --disable-shared',
        'make',
        'cp util/fusermount %s/sbin/fusermount' % prefix,
        'cp lib/.libs/libfuse.a lib' ]
patches = []

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
