#!/usr/bin/python
#
# build fusermount and library files 
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

e = Environment()

url = [ '%s/fuse-2.5.3.tar.gz'%mvpmc.dlprefix0,
	'%s/fuse-2.5.3.tar.gz'%mvpmc.dlprefix1 ]

target = [ bindir + 'fusermount' ]
cmd = [ 'MOUNT_FUSE_PATH="%s"/sbin UDEV_RULES_PATH="%s"/etc/udev/rules.d ./configure --host=powerpc-linux -with-gnu-ld --disable-debug  --enable-lib --enable-util --enable-example=no --disable-kernel-module --disable-shared --prefix="%s"' % (prefix, prefix, prefix),
        'make',
        'make install' ]
patches = []

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
