#!/usr/bin/python
#
# libts_demux
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']

src = [ 'transform.c', 'ts_demux.c' ]

static = env.StaticLibrary('ts_demux', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])
shared = env.SharedLibrary('ts_demux', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])

inst = env.Install(libdir, [ static, shared ])

Return('inst')
