#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']

src = [ 'transform.c', 'ts_demux.c' ]

lib = env.StaticLibrary('ts_demux', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])

inst = env.Install(libdir, lib)

Return('inst')
