#!/usr/bin/python
#
# build libjpeg
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
    config = '--host=powerpc'
else:
    config = ''
  
e = Environment()

url = [ 'http://www.mvpmc.org/dl/jpegsrc.v6b.tar.gz',
        'http://www.ijg.org/files/jpegsrc.v6b.tar.gz' ]

target = [ libdir + 'libjpeg.a' ]
patches = [ 'patches/jpegscale.patch' ]

cmd = [ './configure --prefix=%s %s CFLAGS=-I%s LDFLAGS=-L%s' % (prefix,config,incdir,libdir),
        'make',
        'mkdir -p %s/man/man1' % prefix,
        'make install',
        'make install-lib' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
