#!/usr/bin/python
#
# build dropbear
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
cross = env['CROSS']
downloads = env['DOWNLOADS']
target = env['TARG']

file = downloads + '/dropbear-0.48.1.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'http://matt.ucc.asn.au/dropbear/releases/dropbear-0.48.1.tar.gz'
pwd = os.getcwd()

build = env.Command('../../install/' + target + '/sbin/dropbear', 0,
                    'scons/build_dropbear.sh -d ' + pwd + '/' + target +
                    '/dropbear-0.48.1 -i ' + file + ' ' +
                    '-c ' + cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target + ' ' +
                    '-p patches/100-pubkey_path.patch ' +
                    '-p patches/140-use_dev_urandom.patch ' +
                    '-p patches/makefile.patch ' )

if not os.path.exists(file):
	dl = GetSourceFile(url, '#' + downloads, e)
	env.Depends(build, dl)

Return('build')
