#!/usr/bin/python
#
# build dropbear
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
sbindir = '%s/dongle/install/%s/sbin/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

e = Environment()

url = [ '%s/dropbear-0.48.1.tar.gz'%mvpmc.dlprefix0,
	'%s/dropbear-0.48.1.tar.gz'%mvpmc.dlprefix1,
        'http://matt.ucc.asn.au/dropbear/releases/dropbear-0.48.1.tar.gz' ]

target = [ sbindir + 'dropbear' ]
cmd = [ './configure --disable-zlib --prefix=%s --host=powerpc' % prefix,
        'make',
        'mkdir -p %s/sbin' % prefix,
        'cp dropbearmulti %s/sbin/dropbearmulti' % prefix,
        'ln -sf ./dropbearmulti %s/sbin/dropbear' % prefix,
        'ln -sf ./dropbearmulti %s/sbin/dropbearkey' % prefix,
        'mkdir -p %s/bin' % prefix,
        'ln -sf ../sbin/dropbearmulti %s/bin/scp' % prefix,
        ]
patches = [ 'patches/100-pubkey_path.patch',
            'patches/140-use_dev_urandom.patch',
            'patches/makefile.patch' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
