#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

import os

Import('env')

cc = env['CC']
pwd = os.getcwd()

#glibc = env.Command(cc, 0, 'cd ' + pwd + ' && ./mvpmc-glibc.sh ' + cc)
#Return('glibc')

os.system('cd ' + pwd + ' && ./mvpmc-glibc.sh ' + cc)
