#!/usr/bin/python
#
# libwidget
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']

src = [ 'bitmap.c', 'checkbox.c', 'container.c', 'dialog.c', 'graph.c',
        'image.c', 'menu.c', 'surface.c', 'text.c', 'widget.c', 'utf8.c',
        'image_jpeg.c', 'array.c' ]

static = env.StaticLibrary('widget', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])
shared = env.SharedLibrary('widget', src,
                        CPPPATH = [ env['INCDIR'], env['INSTINCDIR'], '.' ])

inst = env.Install(libdir, [ static, shared ])

Return('inst')
