#!/usr/bin/python
#
# build a52dec
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/a52dec/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

config = '--enable-fixed'
if build_target == 'mvp':
    config = config + ' --host=powerpc'

e = Environment()

url = [ 'http://www.mvpmc.org/dl/a52dec-snapshot.tar.gz',
        'http://liba52.sourceforge.net/files/a52dec-snapshot.tar.gz' ]

target = [ libdir + 'liba52.a',
           incdir + 'a52.h',
           incdir + 'attributes.h',
           incdir + 'audio_out.h',
           incdir + 'mm_accel.h' ]
cmd = [ './configure --prefix=%s %s' % (prefix,config),
        'make',
        'make install' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
