#!/usr/bin/python
#
# build expat
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
downloads = env['DOWNLOADS']
target = env['TARG']

if target == 'mvp':
  cross = '-c ' + env['CROSS']
else:
  cross = ''

file = downloads + '/expat-1.95.8.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'http://www.mvpmc.org/dl/expat-1.95.8.tar.gz'
pwd = os.getcwd()

build = env.Command('../../install/' + target + '/lib/libexpat.a', 0,
                    'scons/build_lib.sh -d ' + pwd + '/' + target +
                    '/expat-1.95.8 -i ' + file + ' ' +
                    cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target + ' '
                    '-C --host=powerpc')

if not os.path.exists(file):
	dl = GetSourceFile(url, '#' + downloads, e)
	env.Depends(build, dl)

env.SideEffect(['../../install/' + target + '/include/expat.h'],
                build)

Return('build')
