#!/usr/bin/python
#
# build expat
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
    config = '--host=powerpc'
else:
    config = '--disable-shared'
  
e = Environment()

url = [ '%s/expat-1.95.8.tar.gz'%mvpmc.dlprefix0,
	'%s/expat-1.95.8.tar.gz'%mvpmc.dlprefix1 ]

target = [ libdir + 'libexpat.a',
           incdir + 'expat.h' ]
cmd = [ './configure --prefix=%s %s' % (prefix,config),
        'make',
        'make install' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
