#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']

src = [ 'demux.c','stream.c' ]

lib = env.StaticLibrary('demux', src, CPPPATH = [ env['INCDIR'], '.' ])

inst = env.Install(libdir, lib)

Return('inst')
