#!/usr/bin/python
#
# libdemux
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
bindir = env['INSTBINDIR']

src = [ 'demux.c','stream.c' ]

static = env.StaticLibrary('demux', src, CPPPATH = [ env['INCDIR'], '.' ])
shared = env.SharedLibrary('demux', src, CPPPATH = [ env['INCDIR'], '.' ])

demuxtest_t = env.Program('demuxtest_t',['demuxtest_t.c'],
    			  CPPPATH=[ env['INCDIR'], '.'],
			  LIBS = [ 'demux','pthread' ],
			  LIBPATH = [ '.' ],
	                  LINKFLAGS = [ '-static' ])

demuxtest = env.Program('demuxtest',['demuxtest.c'],
    			CPPPATH=[ env['INCDIR'], '.'],
			LIBS = [ 'demux','pthread' ],
			LIBPATH = [ '.' ],
	                LINKFLAGS = [ '-static' ])

env.Depends(demuxtest_t, static)
env.Depends(demuxtest, static)

env.Install(bindir,demuxtest)
env.Install(bindir,demuxtest_t)

inst = env.Install(libdir, [ static, shared ])

Return('inst')
