#!/usr/bin/python
#
# build ntpclient
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

e = Environment()

url = [ '%s/ntpclient_2003_194.tar.gz'%mvpmc.dlprefix,
        'http://doolittle.icarus.com/ntpclient/ntpclient_2003_194.tar.gz' ]

target = [ bindir + 'ntpclient' ]
cmd = [ 'make install' ]
patches = [ 'patches/make.patch',
            'patches/error.patch' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
