#!/bin/sh
#
# mvpmc startup script
#

KERNVER=`/bin/uname -r`

#
# Connect to the first available NTP server
#
do_ntp() {
    for i in $1 ; do
	/bin/ntpclient -s -h $i
	if [ $? -eq 0 ] ; then
	    /bin/ntpclient -d -l -h $i &
	    exit 0
	fi
    done
    exit 1
}

#
# Unmount everything in /etc/fstab
#
/bin/umount -a

#
# Unmount the old root device (in case we did a pivot_root already)
#
if [ "$KERNVER" != "2.4.17_mvl21-vdongle" ] ; then
	/bin/umount /oldroot
	/sbin/freeramdisk /dev/ram0
fi

#
# Create the tmpfs filesystem and mount it on top of the squashfs root
# filesystem with unionfs.
#
mount -t tmpfs -o "size=1M" tmpfs /memory
mount -t unionfs -o dirs=/memory=rw:/=ro unionfs /union
cd /union
mkdir live
pivot_root . live

#
# Remount everything read/write
#
/bin/mount -a -o rw

#
# Configure lo0
#
/sbin/ifconfig lo 127.0.0.1

#
# Check for a root password on the kernel command line
#
for i in `cat /proc/cmdline` ; do
    export mvp_$i
done
if [ "$mvp_mvpmc_root" != "" ] ; then
    if [ "$mvp_mvpmc_root" != "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ] ; then
	echo "root:${mvp_mvpmc_root}:0:0:root:/:/bin/sh" > /etc/passwd
    fi
fi

#
# Start telnetd
#
/usr/sbin/telnetd

#
# Load kernel modules
#
if [ "$KERNVER" = "2.4.17_mvl21-vdongle" ] ; then
    insmod os_core
    insmod av_core _fmt=1
    insmod ircombo
    insmod gfx
    insmod osdfb
    insmod ac3_mod
    insmod mvpstb_mod.o mvpmod_major=230
fi

#
# default timezone to US Central
#
TZ=CST+6CDT,M4.1.0/2,M10.5.0/2; export TZ

#
# configure eth0
#
udhcpc
. /etc/udhcpc.config

#
# Make sure the hostname is set to something
#
if [ "$HNAME" = "" ] ; then
    hostname $IP
else
    echo "${IP}    ${HNAME}" >> /etc/hosts
fi

#
# connect to an NTP server, if DHCP has provided a list of servers
#
if [ "$NTP" != "" ] ; then
    do_ntp "$NTP" &
    NTP=
fi

#
# create the user theme directory
#
mkdir /tmp/themes

#
# Download the users config and theme files, if they exist.
#
if [ -n "$DONGLE" ] ; then
    tftp -g -l /etc/dongle.config -r ${DONGLE}.config ${SERVER}
    tftp -g -l /tmp/themes/default.xml -r ${DONGLE}.xml ${SERVER}
    . /etc/dongle.config
fi

#
# if the user has set NTP, restart NTP with their server
#
if [ "$NTP" != "" ] ; then
    killall ntpclient
    do_ntp "$NTP" &
fi

#
# If mvpmc is not running, run it with some reasonable options.
#
if [ -z "`pidof mvpmc`" ] ; then
    if [ -z $SERVER ] ; then
        if [ -z $HOST ] ; then
	    mvpmc -s $IP -c $IP -R "ip=discover" --startup setup --emulate ? &
        else
	    mvpmc -s $HOST -c $HOST --vlc $HOST -R "ip=discover" --emulate ? &
        fi    
    else        
	mvpmc -s $SERVER -c $SERVER --vlc $SERVER -R "ip=discover" --emulate ? &
    fi
fi
