#!/bin/sh
#
# mvpmc startup script
#

KERNVER=`/bin/uname -r`

#
# Connect to the first available NTP server
#
do_ntp() {
    for i in $1 ; do
	/bin/ntpclient -s -h $i
	if [ $? -eq 0 ] ; then
	    /bin/ntpclient -d -l -h $i &
	    exit 0
	fi
    done
    exit 1
}

#
# Unmount everything in /etc/fstab
#
/bin/umount -a

#
# Unmount the old root device (in case we did a pivot_root already)
#
if [ "$KERNVER" != "2.4.17_mvl21-vdongle" ] ; then
	/bin/umount /oldroot
	/sbin/freeramdisk /dev/ram0
fi

#
# Create the tmpfs filesystem and mount it on top of the squashfs root
# filesystem with unionfs.
#
mount -t tmpfs -o "size=1M" tmpfs /memory
if [ "$KERNVER" = "2.4.17_mvl21-vdongle" ] ; then
    insmod -f unionfs
fi
mount -t unionfs -o dirs=/memory=rw:/=ro unionfs /union
cd /union
mkdir live
pivot_root . live

#
# Remount everything read/write
#
/bin/mount -a -o rw

#
# Configure lo0
#
/sbin/ifconfig lo 127.0.0.1

#
# Check for a root password on the kernel command line
#
for i in `cat /proc/cmdline` ; do
    export mvp_$i
done
if [ "$mvp_mvpmc_root" != "" ] ; then
    if [ "$mvp_mvpmc_root" != "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" ] ; then
	echo "root:${mvp_mvpmc_root}:0:0:root:/:/bin/sh" > /etc/passwd
    fi
fi

#
# Start telnetd
#
/usr/sbin/telnetd

#
# Load kernel modules
#
if [ "$KERNVER" = "2.4.17_mvl21-vdongle" ] ; then
    insmod os_core
    insmod av_core _fmt=1
    insmod ircombo
    insmod gfx
    insmod osdfb
    insmod ac3_mod
    insmod mvpstb_mod.o mvpmod_major=230
fi

#
# default timezone to US Central
#
TZ=CST+6CDT,M4.1.0/2,M10.5.0/2; export TZ

#
# configure the default ethernet interface (eth0 is wired, eth1 wireless)
#
ticonfig
if [ $? -eq 0 ] ; then
    #
    # Iterate over the two devices waiting for one of them to get an address
    #
    LEASE=0
    while [ $LEASE -eq 0 ] ; do
	udhcpc -i eth1 -n
	RET=$?
	if [ $RET -ne 0 ] ; then
	    udhcpc -i eth0 -n
	    RET=$?
	fi
	if [ $RET -eq 0 ] ; then
	    LEASE=1
	fi
    done
else
    udhcpc
fi
. /etc/udhcpc.config

#
# Make sure the hostname is set to something
#
if [ "$HNAME" = "" ] ; then
    hostname $IP
else
    echo "${IP}    ${HNAME}" >> /etc/hosts
fi

#
# connect to an NTP server, if DHCP has provided a list of servers
#
if [ "$NTP" != "" ] ; then
    do_ntp "$NTP" &
    NTP=
fi

#
# create the user theme directory
#
mkdir /tmp/themes

#create the "UPnP" folder remove to disable auto djmount
mkdir /uPnP

#
# Download the users config and theme files, if they exist.
#
if [ -n "$DONGLE" ] ; then
    tftp -g -l /etc/dongle.config -r ${DONGLE}.config ${SERVER}
    tftp -g -l /tmp/themes/default.xml -r ${DONGLE}.xml ${SERVER}
    . /etc/dongle.config
    if [ "$NOMVPMC" != "" ] ; then
        exit 0
    fi
fi

#
# if the user has set NTP, restart NTP with their server
#
if [ "$NTP" != "" ] ; then
    killall ntpclient
    do_ntp "$NTP" &
fi



# If mvpmc is not running from the dhcp try other methods


if [ -z "`pidof mvpmc`" ] ; then
    #
    # First try and load dongle.bin.config from the named share on the dongle.bin server
    #     
    vpdread -t
    . /etc/tftp.config
    mkdir /etc/mvpmc
    mount.cifs "//${TFTP}/mvpmc" /etc/mvpmc -o username=guest,password=guest,ro ;
    if [ -e "/etc/mvpmc/dongle.bin.config" ] ; then
        cp /etc/mvpmc/dongle.bin.config /etc/dongle.config
        . /etc/dongle.config
    fi
    #
    # mounting a share failed lets try a tftp from the same server
    #
    if [ -z "`pidof mvpmc`" ] ; then    
        tftp -g -l /etc/dongle.config -r dongle.bin.config ${TFTP}
        tftp -g -l /tmp/themes/default.xml -r dongle.bin.xml ${TFTP}
        . /etc/dongle.config
    fi
    
    #
    # If mvpmc is still not running, run it with some reasonable options.
    #
    if [ -z "`pidof mvpmc`" ] ; then
        if [ -z $SERVER ] ; then
            if [ -z $HOST ] ; then
    	        mvpmc -s ${TFTP} -c ${TFTP} -R "ip=discover" --startup setup --emulate ? &
            else
    	        mvpmc -s $HOST -c $HOST --vlc $HOST -R "ip=discover" --emulate ? &
            fi    
        else        
    	    mvpmc -s $SERVER -c $SERVER --vlc $SERVER -R "ip=discover" --emulate ? &
        fi
    fi    
fi    


