#!/bin/sh
#
# $Id: rcS,v 1.9 2005/12/17 17:57:55 gettler Exp $
#

#
# Mount everything in /etc/fstab
#
/bin/umount -a
/bin/mount -a -o rw

#
# Configure lo0
# eth0 will be autoconfigured by the kernel
#
/sbin/ifconfig lo 127.0.0.1

#
# Start telnetd
#
/usr/sbin/telnetd

#
# Load kernel modules
#
insmod os_core
insmod av_core _fmt=1
insmod ircombo
insmod gfx
insmod osdfb
insmod ac3_mod
insmod mvpstb_mod.o mvpmod_major=230
#insmod xrmod

#default timezone
TZ=CST+6CDT,M4.1.0/2,M10.5.0/2; export TZ

udhcpc
. /etc/udhcpc.config

if [ "$HNAME" = "" ] ; then
    hostname $IP
fi

echo "${IP}    ${HNAME}" >> /etc/hosts
tftp -g -l /etc/dongle.config -r ${DONGLE}.config ${SERVER}
tftp -g -l /tmp/themes/default.xml -r ${DONGLE}.xml ${SERVER}
. /etc/dongle.config
if [ -z "`pidof mvpmc`" ] ; then
    if [ -z $SERVER ] ; then
        if [ -z $HOST ] ; then
	    mvpmc -s $IP -c $IP -R "ip=discover" --startup setup --web-port 80          
        else
	    mvpmc -s $HOST -c $HOST --vlc $HOST -R "ip=discover" --web-port 80
        fi    
    else        
	mvpmc -s $SERVER -c $SERVER --vlc $SERVER -R "ip=discover" --web-port 80
    fi
fi
cd /
