#!/usr/bin/python
#
# build mysql
#

import os
import mvpmc

Import('env','crossroot')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
  cross = env['CROSS']
  host_configs = '--host=ppcbe --with-other-libc='+crossroot+'/lib'
else:
  cross = ''
  host_configs = '--disable-shared'

config_opts = '--without-docs --without-man --without-debug --without-server --without-query-cache  --without-extra-tools --without-perl --with-low-memory --enable-assembler  --with-comment --cache-file=build.cache ' + host_configs

e = Environment()

url = [ '%s/mysql-5.0.21.tar.gz'%mvpmc.dlprefix ]

target = [ libdir + 'mysql/libmysqlclient.a' ]
cmd = [
    'export CXX=%sg++' % cross,
    'export CPP=%scpp' % cross,
    'unset LDFLAGS',
    'unset CROSS',
    'unset CFLAGS',
    'unset CXXFLAGS',
    'export C_INCLUDE_PATH=%s' % incdir,
    'export CFLAGS=-I%s' % incdir,
    'export LDFLAGS=-L%s' % libdir,
    './configure %s --prefix=%s' % (config_opts,prefix),
    'make',
    'make install' ]

if build_target == 'mvp':
    patches = [ 'patches/my_global.h.patch',
                'patches/configure.patch' ]
else:
    patches = [ 'patches/my_global.h.patch' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

env.SideEffect(['../../install/' + build_target + '/include/mysql/mysql.h'],
                build)

Return('build')
