#!/usr/bin/python
#
# build busybox
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)

e = Environment()

url = [ '%s/busybox-1.1.3.tar.bz2'%mvpmc.dlprefix0,
	'%s/busybox-1.1.3.tar.bz2'%mvpmc.dlprefix1,
	'http://busybox.net/downloads/busybox-1.1.3.tar.bz2' ]

target = [ bindir + 'busybox' ]
cmd = [ 'make oldconfig',
	'make install',
	'cp busybox.links %s' % bindir]
patches = [ 'patches/busybox_config.patch',
	    'patches/dhcp.patch',
	    'patches/busybox-1.1.3.patch' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
