#!/usr/bin/python
#
# build busybox
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
bindir = '%s/dongle/install/%s/bin/' % (topdir,build_target)

e = Environment()

url = [ 'http://www.mvpmc.org/dl/busybox-1.1.3.tar.bz2',
	'http://busybox.net/downloads/busybox-1.1.3.tar.bz2' ]

target = [ bindir + 'busybox' ]
cmd = [ 'make oldconfig',
	'make install' ]
patches = [ 'patches/busybox_config.patch',
	    'patches/busybox-1.1.3.patch' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
