#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#
# build busybox
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
cross = env['CROSS']
downloads = env['DOWNLOADS']
target = env['TARG']

file = downloads + '/busybox-1.1.3.tar.bz2'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

url = 'http://busybox.net/downloads/busybox-1.1.3.tar.bz2'
pwd = os.getcwd()

dl = GetSourceFile(url, '#' + downloads, e)

build = env.Command('../../install/' + target + '/bin/busybox', 0,
                    'scons/build_app.sh -d ' + pwd + '/' + target +
                    '/busybox-1.1.3 -i ' + file + ' ' +
                    '-c ' + cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target + ' ' +
                    '-p patches/busybox_config.patch ' +
                    '-p patches/busybox-1.1.3.patch')

env.Depends(build, [ 'patches/busybox_config.patch',
                     'patches/busybox-1.1.3.patch' ])
env.Depends(build, dl)

Return('build')
