#!/usr/bin/python
#
# build zlib
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
    config = '--host=powerpc'
else:
    config = ''
  
e = Environment()

url = [ 'http://www.mvpmc.org/dl/zlib-1.2.3.tar.gz',
        'http://www.zlib.net/zlib-1.2.3.tar.gz' ]

target = [ libdir + 'libz.a' ]

cmd = [ './configure --prefix=%s' % prefix,
        'make',
        'make install' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
