#!/usr/bin/python
#
# build libpng
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
    config = '--host=powerpc'
else:
    config = '--disable-shared'
  
e = Environment()

url = [ 'http://www.mvpmc.org/dl/libpng-1.2.6-config.tar.gz',
        'http://surfnet.dl.sourceforge.net/libpng/libpng-1.2.6-config.tar.gz' ]

target = [ libdir + 'libpng12.a' ]

cmd = [ './configure --prefix=%s %s CFLAGS=-I%s LDFLAGS=-L%s' % (prefix,config,incdir,libdir),
        'make',
        'make install' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
