#!/usr/bin/python
#
# SConscript
#

import os

Import ('env')

mvp = env.Copy()
libdir = mvp['INSTLIBDIR']
mysql_libdir = mvp['INSTLIBDIR'] + '/mysql'
target = mvp['TARG']
toplevel = mvp['TOPLEVEL']
bindir = mvp['INSTBINDIR']

mvp.Append(CCFLAGS = ' -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE')

version = os.system(toplevel + '/src/version.sh ' + toplevel + ' ' + toplevel + '/src')

if target == 'host':
	libx11dir = ['/usr/X11R6/lib']
	libFLAC = []
	libx11 = ['X11', 'pthread', 'rt', 'Xau', 'dl', 'Xdmcp']
	libs = []
	linkflags = '-static'
else:
	libx11dir = []
	libFLAC = ['libFLAC']
	libx11 = []
	libs = [ 'tiwlan' ]
	linkflags = ''

if target == 'mvp':
	splash = mvp.Program('splash',
                             ['splash.c'],
                             CPPPATH = [ env['INCDIR'], env['INSTINCDIR'],
                                         '.', '../include' ],
                             LIBS = ['osd', 'av'],
                             LIBPATH = [ libdir ],
                             LINKFLAGS = [ '' ])

mvpmc = mvp.Program('mvpmc',
                    ['audio.c', 'colorlist.c', 'config.c', 'display.c',
		     'emulate.c', 'fb.c', 'gui.c', 'main.c',
		     'mclient.c', 'mclient_mvpmc.c', 'mclient_cli.c',
		     'mythtv.c', 'mythtv_livetv.c', 'tvguide.c',
		     'playlist.c', 'replaytv.c', 'theme.c', 'video.c',
		     'version.c', 'vlc_control.c', 'web_config.c', 'wss.c',
		     'ticonfig.c', 'vpdread.c' ],
                    CPPPATH = [ env['INCDIR'], env['INSTINCDIR'],
                                '.', '../include' ],
                    LIBS = ['widget', 'nano-X', 'mwengine', 'mwdrivers',
                            'mwfonts', 'replaytv', 'expat',
                            'osd', 'av', 'demux', 'cmyth', 'vnc', 'mysqlclient',
                            'png12', 'z', 'jpeg', 'm', 'gcc', 'pthread',
                            'a52', 'm', 'vorbisidec', 'id3',
                            'ts_demux', 'dvbpsi'] + libFLAC + libx11 + libs,
                    LIBPATH = [ libdir, mysql_libdir ] + libx11dir,
                    LINKFLAGS = linkflags)

if target == 'mvp':
	inst = env.Install(bindir, [ mvpmc, splash ])
else:
	inst = env.Install(bindir, mvpmc)

env.Depends(mvpmc, version)

Return('inst')
