#!/usr/bin/python
#
# $Id: SConscript 20 2006-03-14 05:26:56Z gettler $
#

Import ('env')

dir = env['BUILD_DIR']
target = env['TARG']
libdir = env['INSTLIBDIR']
toplevel = env['TOPLEVEL']

src = [ 'alloc.c','bookmark.c', 'connection.c', 'debug.c', 'event.c',
        'file.c', 'freespace.c', 'keyframe.c', 'mythtv_mysql.c', 'posmap.c', 'proginfo.c',
        'proglist.c', 'rec_num.c', 'recorder.c', 'ringbuf.c', 'socket.c',
        'timestamp.c', 'livetv.c', 'tvguide.c' ]

lib = env.StaticLibrary('cmyth', src, CPPPATH = [ env['INCDIR'],  toplevel + '/dongle/install/mvp/lib/mysql', '.', toplevel + '/dongle/install/mvp/include' ])

inst = env.Install(libdir, lib)

Return('inst')
