#!/usr/bin/python
#
# build libFLAC
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
  configopts = '--host=powerpc --disable-3dnow --disable-thorough-tests --disable-xmms-plugin --disable-oggtest'
else:
  configopts = '--disable-thorough-tests --disable-xmms-plugin --disable-oggtest'

e = Environment()

url = [ 'http://www.mvpmc.org/dl/flac-1.1.3.tar.gz',
        'http://flac.sourceforge.net/files/flac-1.1.3.tar.gz' ]

target = [ libdir + 'libFLAC.a' ]
patches = [ 'flac.patch' ]

cmd = [ './configure %s' % configopts,
        'cp ../../config.h config.h',
        'cd src/libFLAC',
        'make',
        'cp .libs/libFLAC.a %s' % libdir ]

build = mvpmc.OSSBuild(target, url, env, e, cmd, patches)

Return('build')
