#!/usr/bin/python
#
# build libFLAC
#

import os

Import('env')

home = os.environ['HOME']
cc = env['CC']
downloads = env['DOWNLOADS']
target = env['TARG']
libdir = env['INSTLIBDIR']


if target == 'mvp':
  cross = '-c ' + env['CROSS']
  configopts = "\"--host=powerpc --disable-3dnow --disable-thorough-tests --disable-xmms-plugin --disable-oggtest\""
else:
  cross = ''
  configopts = "\"--disable-thorough-tests --disable-xmms-plugin --disable-oggtest\""

file = downloads + '/flac-1.1.3.tar.gz'

e = Environment()
e.Tool('WGet', toolpath=['../../../scons'])

def GetSourceFile(url, output_dir, env):
  '''
  Create a node for a file retrieved via wget.
  This node can be used as a dependency in other rules.
  '''
  # Nab everything after the last slash as the filename
  basefilename = str(url)[str( url).rfind(os.sep) + 1:]
  munged = output_dir + os.sep + basefilename + os.sep + url
  node = env.SourceCode( munged, env.WGet() )
  return node

#url = 'http://flac.sourceforge.net/files/flac-1.1.3.tar.gz'
url = 'http://www.mvpmc.org/dl/flac-1.1.3.tar.gz'
pwd = os.getcwd()

build = env.Command('../../install/' + target + '/lib/libFLAC.a', 0,
                    'scons/build_lib.sh -d ' + pwd + '/' + target +
                    '/flac-1.1.3 -i ' + file + ' ' +
                    cross + ' ' +
                    '-I ' + pwd + '/../../install/' + target + ' ' +
                    '-C ' + configopts + ' ' + 
                    '-L \"-L' + libdir + '\"' + ' ' +
                    '-T ' + target + ' ' +
                    '-p flac.patch' )

if not os.path.exists(file):
	dl = GetSourceFile(url, '#' + downloads, e)
	env.Depends(build, dl)

Return('build')
