#!/usr/bin/python

import os

Import('env')

busybox = env.SConscript(['busybox/SConscript'])
ntp = env.SConscript(['ntpclient/SConscript'])
dropbear = env.SConscript(['dropbear/SConscript'])
fusermount = env.SConscript(['fuse/SConscript'])

apps = env.Depends(ntp, busybox)

Return('apps')
