#!/usr/bin/python

import os

Import('env')

busybox = env.SConscript(['busybox/SConscript'])
ntp = env.SConscript(['ntpclient/SConscript'])
dropbear = env.SConscript(['dropbear/SConscript'])
fuse = env.SConscript([ 'fuse/SConscript'])
djmount = env.SConscript('djmount/SConscript')

apps = env.Depends(ntp, busybox)
apps = env.Depends(djmount,fuse)

Return('apps')
