#!/usr/bin/python
#
# build ncurses
#

import os
import mvpmc

Import('env')

build_target = env['TARG']
topdir = env['TOPDIR']
libdir = '%s/dongle/install/%s/lib/' % (topdir,build_target)
incdir = '%s/dongle/install/%s/include/' % (topdir,build_target)
prefix = '%s/dongle/install/%s' % (topdir,build_target)

if build_target == 'mvp':
    config = '--host=ppcbe'
    cross = env['CROSS']
else:
    config = ''
    cross = ''

e = Environment()

url = [ '%s/ncurses-5.5.tar.gz'%mvpmc.dlprefix,
        'http://ftp.gnu.org/pub/gnu/ncurses/ncurses-5.5.tar.gz' ]

target = [ libdir + 'libncurses.a' ]
cmd = [ 'export CXX=%sg++' % cross,
        './configure --prefix=%s %s' % (prefix,config),
        'make libs',
        'make install.libs' ]

build = mvpmc.OSSBuild(target, url, env, e, cmd)

Return('build')
